/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.maa.algo.ui;

import com.maa.algo.enums.DistanceType;
import com.maa.algo.enums.GenType;
import com.maa.algo.enums.MiningType;
import com.maa.algo.enums.VisGNodeType;
import com.maa.algo.ikasl.auxi.GNodeVisualizer;
import com.maa.algo.ikasl.core.IKASLRun;
import com.maa.algo.listeners.TaskListener;
import com.maa.algo.objects.GNode;
import com.maa.algo.objects.GenLayer;
import com.maa.algo.objects.VisGNode;
import com.maa.algo.utils.AlgoParameters;
import com.maa.algo.utils.Constants;
import com.maa.algo.utils.FileReader;
import com.maa.algo.utils.FileWriter;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.io.File;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Thushan Ganegedara
 */
public class MainWindow extends javax.swing.JFrame implements TaskListener {

    private String inputDir;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        iRun = new IKASLRun(this);
        initComponents();
        this.setLocationRelativeTo(null);

    }
    IKASLRun iRun;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputDirTxt = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sfTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nrTxt = new javax.swing.JTextField();
        lrTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iterTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aggCombo = new javax.swing.JComboBox();
        lcTxt = new javax.swing.JTextField();
        htTxt = new javax.swing.JTextField();
        runOneBtn = new javax.swing.JButton();
        runAllBtn = new javax.swing.JButton();
        statusLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTxt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        saveWeightsBtn = new javax.swing.JButton();
        intSectLinkBtn = new javax.swing.JButton();
        visualizeBtn = new javax.swing.JButton();
        clrBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        patternRBtn = new javax.swing.JRadioButton();
        anomalyRBtn = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        distCombo = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        minLengthTxt = new javax.swing.JTextField();
        minCountTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IKASL v2");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(browseBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBtn)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("GSOM Options"));

        jLabel1.setText("Spread Factor");

        sfTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sfTxt.setText("0.5");

        jLabel2.setText("Neighborhood R");

        nrTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nrTxt.setText("4");

        lrTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lrTxt.setText("0.25");

        jLabel3.setText("Learning Rate");

        iterTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iterTxt.setText("100");

        jLabel4.setText("Iterations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iterTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(sfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(iterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("IKASL Options"));

        jLabel5.setText("Learning Cycles");

        jLabel6.setText("Hit Threshold");

        jLabel7.setText("Aggregation");

        aggCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AVG", "FUZZY" }));
        aggCombo.setSelectedIndex(1);

        lcTxt.setText("3");

        htTxt.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(htTxt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aggCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(aggCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(htTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        runOneBtn.setText("Run 1 Step");
        runOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runOneBtnActionPerformed(evt);
            }
        });

        runAllBtn.setText("Run All Steps");
        runAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runAllBtnActionPerformed(evt);
            }
        });

        statusLbl.setText("Status");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logTxt.setColumns(20);
        logTxt.setRows(5);
        jScrollPane1.setViewportView(logTxt);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualization and Save Options"));

        jButton1.setText("Node Informatio Utility");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveWeightsBtn.setText("Save Node Weights");
        saveWeightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveWeightsBtnActionPerformed(evt);
            }
        });

        intSectLinkBtn.setText("Full Intersection Links");
        intSectLinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intSectLinkBtnActionPerformed(evt);
            }
        });

        visualizeBtn.setText("Visualize");
        visualizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(saveWeightsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(intSectLinkBtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(visualizeBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(saveWeightsBtn)
                    .addComponent(intSectLinkBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visualizeBtn))
        );

        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Make sure attribute weights are in weights.txt");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Make sure Min,Max bounds specified in bounds.txt");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        buttonGroup1.add(patternRBtn);
        patternRBtn.setSelected(true);
        patternRBtn.setText("General Patterns");

        buttonGroup1.add(anomalyRBtn);
        anomalyRBtn.setText("Anomaly Patterns");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Distance"));

        jLabel10.setText("Distance Type: ");

        distCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manhattan", "Euclidean", "Fractional 0.5", "Fractional 0.25" }));
        distCombo.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(distCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Intersection Links"));

        jLabel.setText("Min Length");

        jLabel12.setText("Min Count");

        minLengthTxt.setText("3");

        minCountTxt.setText("5");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minLengthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(minLengthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(minCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anomalyRBtn)
                            .addComponent(patternRBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(statusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(runOneBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(runAllBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clrBtn)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patternRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anomalyRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runAllBtn)
                            .addComponent(runOneBtn)
                            .addComponent(clrBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runAllBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runAllBtnActionPerformed

    private void runOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runOneBtnActionPerformed
        readAndSetAlgoParameters();
        iRun.runSingleStep();
    }//GEN-LAST:event_runOneBtnActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        JFileChooser chooser = new JFileChooser(".");//E:\GSOM2_v3\GSOM2
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int choice = chooser.showOpenDialog(null);

        if (choice != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File chosenFile = chooser.getSelectedFile();
        //JOptionPane.showMessageDialog(null,chosenFile.getAbsolutePath());
        inputDirTxt.setText(chosenFile.getAbsolutePath());
        inputDir = inputDirTxt.getText();
        iRun.setDir(inputDir);
    }//GEN-LAST:event_browseBtnActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        iRun.clearAll();
        logTxt.setText("");
    }//GEN-LAST:event_clrBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NodeInfoUtility niu = new NodeInfoUtility();
        niu.setData(iRun);
        niu.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveWeightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveWeightsBtnActionPerformed
        ArrayList<GenLayer> allGlayers = iRun.getAllGenLayers();

        FileWriter fw = new FileWriter();
        fw.initialize("Node Weights.txt");
        DecimalFormat df = new DecimalFormat("#.000");

        int currLayer = 0;
        for (GenLayer gL : allGlayers) {
            fw.writeData("Learn Cycle =======================\n");
            for (Map.Entry<String, GNode> e : gL.getMap().entrySet()) {
                //for each learn cycle, nodes printed should be from that particular learn cycle only
                //(i.e. cannot be from previous learn cycles)
                if (Integer.parseInt(e.getKey().split(Constants.I_J_TOKENIZER)[0]) == currLayer) {
                    String str = e.getKey() + "\t";
                    for (double d : e.getValue().getWeights()) {
                        str += df.format(d) + "\t";
                    }
                    fw.writeData(str);
                }
            }
            fw.writeData("=====================================\n");
            currLayer++;
        }

        fw.close();
    }//GEN-LAST:event_saveWeightsBtnActionPerformed

    private void intSectLinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intSectLinkBtnActionPerformed
        int minCount = Integer.parseInt(minCountTxt.getText());
        int minLength = Integer.parseInt(minLengthTxt.getText());
        iRun.printFullIntersectionLinks(minLength, minCount);
        iRun.getVisNodes();
    }//GEN-LAST:event_intSectLinkBtnActionPerformed

    private void visualizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeBtnActionPerformed

        GNodeVisualizer viser = new GNodeVisualizer();
        final ArrayList<VisGNode> allVisNodes = viser.assignVisCoordinatesToGNodes(iRun.getAllGenLayers());

        int widthFreeSpace = 50;
        int heightFreeSpace = 50;
        final int btnWidth = 25;
        final int btnHeight = 25;
        final int hGap = 50;
        final int vGap = 100;

        int[] maxXY = getMaxCoordsVisNodes(allVisNodes);

        int frameWidth = ((maxXY[0] + 1) * btnWidth) + (maxXY[0] * hGap) + (hGap / 2);
        int frameHeight = ((maxXY[1] + 1) * btnHeight) + (maxXY[1] * vGap) + (vGap / 2);

        JPanel btnPanel = new JPanel() {
            public void paintComponent(Graphics g) {
                for (VisGNode gn : allVisNodes) {
                    int[] xy = getVisCoordinates(gn.getCoordinates()[0], gn.getCoordinates()[1],
                            btnWidth, btnHeight, hGap, vGap);
                    if (gn.getParent() != null) {
                        int[] pXY = getVisCoordinates(gn.getParent().getCoordinates()[0], gn.getParent().getCoordinates()[1],
                                btnWidth, btnHeight, hGap, vGap);
                        g.drawLine(xy[0], xy[1], pXY[0], pXY[1]);

                    }
                }

            }
        };
        btnPanel.setPreferredSize(new Dimension(frameWidth, frameHeight));
        btnPanel.setLayout(new GridLayout(maxXY[1] + 1, maxXY[0] + 1, hGap, vGap));

        for (int y = 0; y <= maxXY[1]; y++) {
            for (int x = 0; x <= maxXY[0]; x++) {

                if (allVisNodes.contains(new VisGNode(null, x, y, null, VisGNodeType.HIT))) {

                    JButton btn = new JButton();
                    int gnIdx = allVisNodes.indexOf(new VisGNode(null, x, y, null, VisGNodeType.HIT));
                    VisGNode vgn = allVisNodes.get(gnIdx);
                    GNode gn = allVisNodes.get(gnIdx).getGNode();
                    if(vgn.getParent()!=null){
                    btn.setToolTipText(x + "," + y + ";" + vgn.getParent().getCoordinates()[0] + "," + vgn.getParent().getCoordinates()[1]
                            + ";" + gn.getLc() + "," + gn.getId() + ";" + gn.getParentID());
                    }
                    btn.setSize(new Dimension(btnWidth, btnHeight));
                    btnPanel.add(btn);
                } else {
                    JLabel lbl = new JLabel();
                    lbl.setSize(btnWidth, btnHeight);
                    btnPanel.add(lbl);
                }
            }
        }

        //btnPanel.setBounds(0, 0, frameWidth,frameHeight);
        JFrame visFrame = new JFrame();
        visFrame.setSize(frameWidth, frameHeight);
        visFrame.getContentPane().add(btnPanel);
        visFrame.setVisible(true);
    }//GEN-LAST:event_visualizeBtnActionPerformed

    private int[] getVisCoordinates(int x, int y, int btnWidth, int btnHeight, int hGap, int vGap) {
        double visX = ((double) btnWidth) / 2 + ((hGap + btnWidth) * x);
        double visY = ((double) btnHeight) / 2 + ((vGap + btnHeight) * y);

        return new int[]{(int) visX, (int) visY};
    }

    private int[] getMaxCoordsVisNodes(ArrayList<VisGNode> visNodes) {
        int maxX = 0;
        int maxY = 0;
        for (VisGNode vgn : visNodes) {
            if (vgn.getCoordinates()[0] > maxX) {
                maxX = vgn.getCoordinates()[0];
            }
            if (vgn.getCoordinates()[1] > maxY) {
                maxY = vgn.getCoordinates()[1];
            }
        }
        return new int[]{maxX, maxY};
    }

    private void readAndSetAlgoParameters() {
        if (distCombo.getSelectedIndex() == 0) {
            AlgoParameters.dType = DistanceType.MANHATTAN;
        } else if (distCombo.getSelectedIndex() == 1) {
            AlgoParameters.dType = DistanceType.EUCLIDEAN;
        } else if (distCombo.getSelectedIndex() == 2) {
            AlgoParameters.dType = DistanceType.FRACT_HALF;
        } else if (distCombo.getSelectedIndex() == 3) {
            AlgoParameters.dType = DistanceType.FRACT_QUARTER;
        }

        AlgoParameters.SPREAD_FACTOR = Double.parseDouble(sfTxt.getText());
        AlgoParameters.START_LEARNING_RATE = Double.parseDouble(lrTxt.getText());
        AlgoParameters.MAX_NEIGHBORHOOD_RADIUS = Double.parseDouble(nrTxt.getText());
        AlgoParameters.MAX_ITERATIONS = Integer.parseInt(iterTxt.getText());

        AlgoParameters.LEARN_CYCLES = Integer.parseInt(lcTxt.getText());
        AlgoParameters.HIT_THRESHOLD = Integer.parseInt(htTxt.getText());

        if (aggCombo.getSelectedIndex() == 0) {
            AlgoParameters.gType = GenType.AVG;
        } else if (aggCombo.getSelectedIndex() == 1) {
            AlgoParameters.gType = GenType.FUZZY;
        }

        if (patternRBtn.isSelected()) {
            AlgoParameters.MINING_TYPE = MiningType.GENERAL;
        } else if (anomalyRBtn.isSelected()) {
            AlgoParameters.MINING_TYPE = MiningType.ANOMALY;
        }
        FileReader fr = new FileReader();
        ArrayList<String> minMaxList = fr.readLines(inputDir + "\\" + Constants.BOUNDS_FILE);

        String[] minStr = minMaxList.get(0).split(Constants.INPUT_TOKENIZER);
        double[] min = new double[minStr.length];

        String[] maxStr = minMaxList.get(1).split(Constants.INPUT_TOKENIZER);
        double[] max = new double[maxStr.length];

        for (int i = 0; i < minStr.length; i++) {
            min[i] = Double.parseDouble(minStr[i]);
            max[i] = Double.parseDouble(maxStr[i]);
        }

        AlgoParameters.MIN_BOUNDS = min;
        AlgoParameters.MAX_BOUNDS = max;

        String weightsStr = fr.readLines(inputDir + "\\" + Constants.WEIGHT_FILE).get(0);
        String[] weightTokens = weightsStr.split(Constants.INPUT_TOKENIZER);
        double[] weights = new double[weightTokens.length];

        for (int i = 0; i < weightTokens.length; i++) {
            weights[i] = Double.parseDouble(weightTokens[i]);
        }

        AlgoParameters.ATTR_WEIGHTS = weights;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aggCombo;
    private javax.swing.JRadioButton anomalyRBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clrBtn;
    private javax.swing.JComboBox distCombo;
    private javax.swing.JTextField htTxt;
    private javax.swing.JTextField inputDirTxt;
    private javax.swing.JButton intSectLinkBtn;
    private javax.swing.JTextField iterTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lcTxt;
    private javax.swing.JTextArea logTxt;
    private javax.swing.JTextField lrTxt;
    private javax.swing.JTextField minCountTxt;
    private javax.swing.JTextField minLengthTxt;
    private javax.swing.JTextField nrTxt;
    private javax.swing.JRadioButton patternRBtn;
    private javax.swing.JButton runAllBtn;
    private javax.swing.JButton runOneBtn;
    private javax.swing.JButton saveWeightsBtn;
    private javax.swing.JTextField sfTxt;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton visualizeBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void logMessage(String msg) {
        logTxt.append(msg + "\n");
    }

    @Override
    public void updateStatus(String msg) {
        statusLbl.setText(msg);
    }

    @Override
    public void outputMsgBox(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
}
