/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.maa.ui;

import com.maa.enums.AggregationType;
import com.maa.io.FileUtils;
import com.maa.listeners.ConfigCompleteListener;
import com.maa.models.AlgoParamModel;
import com.maa.models.BasicParamModel;
import com.maa.models.ParamModel;
import com.maa.utils.ImportantFileNames;
import com.maa.xml.AlgoXMLWriter;
import com.maa.xml.BasicXMLParser;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Thush
 */
public class AlgoParameterUI extends javax.swing.JFrame {

    private Map<String, AlgoParamModel> streamParamMap;
    ArrayList<String> streamIDs;

    /**
     * Creates new form BasicParameterUI
     */
    public AlgoParameterUI() {
        initComponents();
        setLocationRelativeTo(null);
        
        streamParamMap = new HashMap<>();
        BasicXMLParser bXMLParser = new BasicXMLParser();
        BasicParamModel bPModel = (BasicParamModel) bXMLParser.parseXML();
        streamIDs = bPModel.getStreamIDs();

        for (String s : bPModel.getStreamIDs()) {
            streamsCmb.addItem(s);
        }
        String btnText = "Save Values for Stream " + (String) streamsCmb.getSelectedItem();
        saveForStreamBtn.setText(btnText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        cancelTxt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sfTxt = new javax.swing.JTextField();
        nrTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lrTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        iterTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        htTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        aggrCmb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        streamsCmb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dimTxt = new javax.swing.JTextField();
        sameValChk = new javax.swing.JCheckBox();
        saveForStreamBtn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Introduction"));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thush\\Documents\\NetBeansProjects\\MAA\\images\\introduction.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backBtn.setText("Back");

        finishBtn.setText("Finish");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        cancelTxt.setText("Cancel");
        cancelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTxtActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Step 4/4");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Algorithm Parameters"));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thush\\Documents\\NetBeansProjects\\MAA\\images\\basic.jpg")); // NOI18N

        jLabel6.setText("Spread Factor:");

        sfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfTxtActionPerformed(evt);
            }
        });

        nrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Neighborhood Radius:");

        lrTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Learning Rate:");

        iterTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterTxtActionPerformed(evt);
            }
        });

        jLabel9.setText("Iterations:");

        jLabel10.setText("Hit Threshold:");

        htTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Aggregation:");

        aggrCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fuzzy", "Average", "None" }));
        aggrCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggrCmbActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Stream:");

        streamsCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamsCmbActionPerformed(evt);
            }
        });

        jLabel5.setText("<html>\nPlease make sure you have specified bounds for each dimension in <b>bounds.txt</b> located in ... <br/>\nPlease make sure you have specified weights for each dimension in <b>weights.txt</b> located in ...\n</html>");

        jLabel12.setText("Dimensions:");

        dimTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimTxtActionPerformed(evt);
            }
        });

        sameValChk.setText("Use these values for all the streams");
        sameValChk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sameValChkItemStateChanged(evt);
            }
        });

        saveForStreamBtn.setText("Button");
        saveForStreamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveForStreamBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(streamsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(59, 59, 59)
                        .addComponent(dimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(sameValChk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveForStreamBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(44, 44, 44)
                                .addComponent(sfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(nrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(lrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(iterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aggrCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(htTxt))))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(streamsCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(dimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(htTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(aggrCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(saveForStreamBtn)
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(sameValChk))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finishBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelTxt))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelTxt)
                    .addComponent(finishBtn)
                    .addComponent(backBtn)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfTxtActionPerformed

    private void nrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrTxtActionPerformed

    private void lrTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lrTxtActionPerformed

    private void iterTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iterTxtActionPerformed

    private void htTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_htTxtActionPerformed

    private void aggrCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggrCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggrCmbActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed

        AlgoXMLWriter aXMLWriter = new AlgoXMLWriter();

        if (!sameValChk.isSelected() &&  streamParamMap.keySet().containsAll(streamIDs)) {
            String loc = ImportantFileNames.CONFIG_DIRNAME + File.separator + ImportantFileNames.ALGO_CONFIG_FILENAME;
            aXMLWriter.writeMultipleXML(new ArrayList<String>(streamParamMap.keySet()), new ArrayList<AlgoParamModel>(streamParamMap.values()), loc);

            cListener.allConfigCompleted();
        }
        if(sameValChk.isSelected()){
            //use same value for all the elements
        }

    }//GEN-LAST:event_finishBtnActionPerformed
    ConfigCompleteListener cListener;

    public void setListener(ConfigCompleteListener cListener) {
        this.cListener = cListener;
    }

    public ArrayList<AlgoParamModel> getAlgoParamModels() {
        return new ArrayList<AlgoParamModel>(streamParamMap.values());
    }

    private void cancelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTxtActionPerformed
        FileUtils.cleanConfigDir();
    }//GEN-LAST:event_cancelTxtActionPerformed

    private void dimTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimTxtActionPerformed

    private void streamsCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streamsCmbActionPerformed
        String btnText = "Save Values for Stream " + (String) streamsCmb.getSelectedItem();
        saveForStreamBtn.setText(btnText);
    }//GEN-LAST:event_streamsCmbActionPerformed

    private void sameValChkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sameValChkItemStateChanged
        if (sameValChk.isSelected()) {
            streamsCmb.setEnabled(false);
        } else {
            streamsCmb.setEnabled(true);
        }
    }//GEN-LAST:event_sameValChkItemStateChanged

    private void saveForStreamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveForStreamBtnActionPerformed
        String stream = streamIDs.get(streamsCmb.getSelectedIndex());
        double sf = Double.parseDouble(sfTxt.getText());
        double lr = Double.parseDouble(lrTxt.getText());
        int iter = Integer.parseInt(iterTxt.getText());
        int nr = Integer.parseInt(nrTxt.getText());
        int ht = Integer.parseInt(htTxt.getText());
        int dim = Integer.parseInt(dimTxt.getText());
        AggregationType aggr = AggregationType.FUZZY;
        if (aggrCmb.getSelectedIndex() == 1) {
            aggr = AggregationType.AVERAGE;
        } else if (aggrCmb.getSelectedIndex() ==2){
            aggr = AggregationType.NONE;
        }
        AlgoParamModel pModel = new AlgoParamModel(stream, sf, nr, lr, iter, ht, aggr,dim);
        streamParamMap.put(stream, pModel);
    }//GEN-LAST:event_saveForStreamBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgoParameterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgoParameterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgoParameterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgoParameterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgoParameterUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aggrCmb;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelTxt;
    private javax.swing.JTextField dimTxt;
    private javax.swing.JButton finishBtn;
    private javax.swing.JTextField htTxt;
    private javax.swing.JTextField iterTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lrTxt;
    private javax.swing.JTextField nrTxt;
    private javax.swing.JCheckBox sameValChk;
    private javax.swing.JButton saveForStreamBtn;
    private javax.swing.JTextField sfTxt;
    private javax.swing.JComboBox streamsCmb;
    // End of variables declaration//GEN-END:variables
}
